title: Psy126 - Test Theory and Test Construction with Python
author: Leonardo Zaggia
logo: 4.png
copyright: "2025 Leonardo Zaggia"
# Useful reference for creating the config: https://jupyterbook.org/en/stable/customize/config.html

# Do not execute notebooks
execute:
  execute_notebooks: "off"

exclude_patterns: [".venv", "README.md", test.ipynb, test.py]

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - book/references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/leonardozaggia/Psy126-Python
  branch: main

# Add GitHub buttons to your book
html:
  home_page_in_navbar: false
  use_issues_button: true
  use_repository_button: true
  baseurl: https://github.com/leonardozaggia/Psy126-Python
  extra_css:
    - _static/custom.css

# Google colab launch button
launch_buttons:
  colab_url: "https://colab.research.google.com"

# Make the book's default style dark
sphinx:
  html_context:
    default_mode: dark